apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: virtual-dm-ingress
  labels:
    app: virtual-dm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: virtual-dm.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: virtual-dm-service
            port:
              number: 80
