apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/Altinity/clickhouse-operator/release-0.25.1/deploy/operator/clickhouse-operator-install-bundle.yaml
  - deployment.yaml
  - service.yaml
  - clickhouse-installation.yaml

commonLabels:
  app: virtual-dm
  version: v1
